name: Selenium Tests
 
on:
  push:
    branches: [ main ]
  pull_request:
 
jobs:
  test:
    runs-on: ubuntu-latest
 
    steps:
      - name:  Checkout repo
        uses: actions/checkout@v4
 
      - name:  Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
 
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install faker
 
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
 
      - name:  Install ChromeDriver
        uses: nanasess/setup-chromedriver@v2
 
      - name: Run tests
        run: pytest